## Saving frozen graph for serving

In [2]:
import tensorflow.compat.v1 as tf
import os

tf.compat.v1.disable_eager_execution()

os.chdir('efficientdet_files/efficientdet')

In [3]:
MODEL = 'efficientdet-d0'  #@param
ckpt_path = os.path.join(os.getcwd(), MODEL)
print('Use model in {}'.format(ckpt_path))

Use model in /app/notebooks/efficientdet_files/efficientdet/efficientdet-d0


In [4]:
import inference 

# Load inference model
net = inference.ServingDriver(MODEL, ckpt_path, batch_size=1, min_score_thresh=0.4, max_boxes_to_draw=200, line_thickness=2)
net.build()

Instructions for updating:
Use `tf.cast` instead.
Instructions for updating:
Use `tf.cast` instead.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


Instructions for updating:
If using Keras pass *_constraint arguments to layers.


Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`


Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
3 ops no flops stats due to incomplete shapes.


Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.


Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.


Instructions for updating:
Please use `layer.__call__` method instead.


Instructions for updating:
Please use `layer.__call__` method instead.


Instructions for updating:
Use keras.layers.MaxPooling2D instead.


Instructions for updating:
Use keras.layers.MaxPooling2D instead.


Instructions for updating:
Use `tf.keras.layers.SeparableConv2D` instead.


Instructions for updating:
Use `tf.keras.layers.SeparableConv2D` instead.
3 ops no flops stats due to incomplete shapes.
3 ops no flops stats due to incomplete shapes.


Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.


Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.


INFO:tensorflow:Restoring parameters from /app/notebooks/efficientdet_files/efficientdet/efficientdet-d0/model


INFO:tensorflow:Restoring parameters from /app/notebooks/efficientdet_files/efficientdet/efficientdet-d0/model


{'image_files': <tf.Tensor 'image_files:0' shape=(None,) dtype=string>,
 'image_arrays': <tf.Tensor 'image_arrays:0' shape=(None, None, None, None) dtype=uint8>,
 'prediction': <tf.Tensor 'detections:0' shape=(1, None, 7) dtype=float32>}

In [5]:
save_path = '../../efficientdet_files_frozen'
net.export(save_path)

Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.


INFO:tensorflow:Assets added to graph.


INFO:tensorflow:Assets added to graph.


INFO:tensorflow:No assets to write.


INFO:tensorflow:No assets to write.


INFO:tensorflow:SavedModel written to: ../../efficientdet_files_frozen/saved_model.pb


INFO:tensorflow:SavedModel written to: ../../efficientdet_files_frozen/saved_model.pb


Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`


Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`


Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`


Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`


INFO:tensorflow:Froze 709 variables.


INFO:tensorflow:Froze 709 variables.


INFO:tensorflow:Converted 709 variables to const ops.


INFO:tensorflow:Converted 709 variables to const ops.


## Inference example from frozen graph



In [1]:
# Restart notebook here, to use TF2 and load frozen model
import tensorflow as tf
save_path = './efficientdet_files_frozen'

loaded = tf.saved_model.load(save_path)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [2]:
import numpy as np 
import PIL

raw_images = []
raw_images.append(np.array(PIL.Image.open('./images/img1.jpg')))

In [3]:
infer = loaded.signatures["serving_default"]

In [4]:
predictions = infer(tf.expand_dims(raw_images[0], axis=0))

In [5]:
predictions_numpy = predictions['detections:0'].numpy()

In [6]:
boxes = predictions_numpy[0][:, 1:5].astype(int)
classes = predictions_numpy[0][:, 6].astype(int)
scores = predictions_numpy[0][:, 5]

In [7]:
boxes

array([[157, 441, 103,  57],
       [210, 414,  71,  85],
       [132, 279, 105,  76],
       [110, 149,  94,  51],
       [173, 163,  73, 100],
       [124, 182, 104,  74],
       [181, 271,  79, 114],
       [138,  63,  78,  98],
       [ 96,  76,  95,  68],
       [118,   0,  63,  49],
       [181, 322,  80,  74],
       [122, 340,  79,  48],
       [ 82,   1,  75,  44],
       [278, 131,  54,  45],
       [290, 224,  41,  41],
       [313, 307,  19,  40]])

In [8]:
classes

array([1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1])

In [9]:
scores

array([0.7388182 , 0.71016717, 0.70702654, 0.66223276, 0.6618915 ,
       0.6526376 , 0.64912826, 0.62456447, 0.6001033 , 0.5811202 ,
       0.57909834, 0.5693069 , 0.5393311 , 0.4636381 , 0.4613469 ,
       0.40417287], dtype=float32)